/**
 * Tests for poetry.lock and Pipfile.lock parsers
 */

import { describe, expect, test } from 'bun:test';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { parseDependencies } from '../scanner/dependency-parser.js';
import type { DependencyFile } from '../scanner/types.js';

describe('poetry.lock parser', () => {
  test('should parse poetry.lock dependencies', async () => {
    const testDir = join(tmpdir(), `wtmp-test-poetry-${Date.now()}`);
    await mkdir(testDir, { recursive: true });

    const poetryLockContent = `# This file is automatically @generated by Poetry and should not be changed by hand.
[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
category = "main"
optional = false
python-versions = ">=3.7"

[[package]]
name = "pytest"
version = "7.4.0"
description = "pytest: simple powerful testing with Python"
category = "dev"
optional = false
python-versions = ">=3.7"

[[package]]
name = "urllib3"
version = "2.0.7"
description = "HTTP library with thread-safe connection pooling"
category = "main"
optional = false
python-versions = ">=3.7"

[metadata]
lock-version = "2.0"
python-versions = "^3.11"
content-hash = "abc123"
`;

    const filePath = join(testDir, 'poetry.lock');
    await writeFile(filePath, poetryLockContent);

    const file: DependencyFile = {
      path: filePath,
      type: 'poetry.lock',
      relativePath: 'poetry.lock',
    };

    const deps = await parseDependencies([file]);

    expect(deps.length).toBe(3);

    const requests = deps.find(d => d.name === 'requests');
    expect(requests).toBeDefined();
    expect(requests?.version).toBe('2.31.0');
    expect(requests?.isDev).toBe(false);
    expect(requests?.isPinned).toBe(true);
    expect(requests?.ecosystem).toBe('pypi');

    const pytest = deps.find(d => d.name === 'pytest');
    expect(pytest).toBeDefined();
    expect(pytest?.isDev).toBe(true);
    expect(pytest?.version).toBe('7.4.0');

    const urllib3 = deps.find(d => d.name === 'urllib3');
    expect(urllib3).toBeDefined();
    expect(urllib3?.isDev).toBe(false);

    await rm(testDir, { recursive: true, force: true });
  });
});

describe('Pipfile.lock parser', () => {
  test('should parse Pipfile.lock dependencies', async () => {
    const testDir = join(tmpdir(), `wtmp-test-pipfile-${Date.now()}`);
    await mkdir(testDir, { recursive: true });

    const pipfileLockContent = `{
    "_meta": {
        "hash": "abc123",
        "pipfile-spec": 6,
        "requires": {"python_version": "3.11"},
        "sources": []
    },
    "default": {
        "requests": {
            "hashes": ["sha256:abc123"],
            "index": "pypi",
            "version": "==2.31.0"
        },
        "flask": {
            "hashes": ["sha256:def456"],
            "index": "pypi",
            "version": "==2.3.2"
        }
    },
    "develop": {
        "pytest": {
            "hashes": ["sha256:ghi789"],
            "index": "pypi",
            "version": "==7.4.0"
        },
        "black": {
            "hashes": ["sha256:jkl012"],
            "index": "pypi",
            "version": "==23.7.0"
        }
    }
}`;

    const filePath = join(testDir, 'Pipfile.lock');
    await writeFile(filePath, pipfileLockContent);

    const file: DependencyFile = {
      path: filePath,
      type: 'Pipfile.lock',
      relativePath: 'Pipfile.lock',
    };

    const deps = await parseDependencies([file]);

    expect(deps.length).toBe(4);

    const requests = deps.find(d => d.name === 'requests');
    expect(requests).toBeDefined();
    expect(requests?.version).toBe('2.31.0');
    expect(requests?.isDev).toBe(false);
    expect(requests?.isPinned).toBe(true);

    const flask = deps.find(d => d.name === 'flask');
    expect(flask).toBeDefined();
    expect(flask?.version).toBe('2.3.2');

    const pytest = deps.find(d => d.name === 'pytest');
    expect(pytest).toBeDefined();
    expect(pytest?.isDev).toBe(true);
    expect(pytest?.version).toBe('7.4.0');

    const black = deps.find(d => d.name === 'black');
    expect(black).toBeDefined();
    expect(black?.isDev).toBe(true);

    await rm(testDir, { recursive: true, force: true });
  });
});
